
package:
  steps:
    - semver
    - opspkg:
        artifact.id: asl
        fileset.includes: >-
          run.xml,
          lib/**/*,
          scripts/**/*,
          tools/**/*,
          VERSION